### ISSUE TITLE
RouDi segfault in introspection mempool port

### ISSUE THREAD

**Issue by dkroenke** [eclipse/iceoryx#314] opened 2020-09-24 11:24 UTC
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 7.5.0

**Observed result or behaviour:**
When starting RouDi, some applications and the Introspection. An error in RouDi comes up:
[ Error ]: There is no shared memory available to allocate from! Terminating!

The mempool receiver fifo in introspection is higher as the mempool configs.

**Expected result or behaviour:**
RouDi shall not terminate when starting the introspection

**Conditions where it occurred / Performed steps:**
When starting RouDi, some applications and the Introspection.

**Comment by marthtz** [comment] 2020-10-29 14:33
Duplicate of #322

**Closed by marthtz** 2020-10-29 14:33 UTC
Labels: bug
