### ISSUE TITLE
Compilation error with GCC 9.1.0

### ISSUE THREAD

**Issue by mossmaurice** [eclipse/iceoryx#1] opened 2019-10-24 11:39 UTC
**Operating system:** Arch Linux

**Compiler version:** GCC 9.1.0

**Observed result or behaviour:** Software does not compile (./iceoryx_utils/cxx/variant.hpp:231 error: requested alignment is not an integer constant)  

**Expected result or behaviour:** Software shall compile

**Conditions where it occurred / Performed steps:** run ./tools/iceoryx_build_test.sh

**Comment by elfenpiff** [comment] 2019-10-24 14:49
Hey @mossmaurice,
thanks for reporting this issue. This is caused by a compiler bug found in GCC 9.1.0 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90736) and is already fixed in GCC 9.2 and above. The solution here would be to not use GCC 9.1.0 and instead use GCC 5 or above.

I would close the bug for now since this would be some effort to circumvent this already fixed compiler bug. If it stays an issue then please report the bug again with a short reasoning why the broken GCC 9.1.0 version should be supported.

**Closed by elfenpiff** 2019-10-24 14:49 UTC
Labels: bug
