### ISSUE TITLE
document our error handling strategy

### ISSUE THREAD

**Issue by MatthiasKillat** [eclipse/iceoryx#313] opened 2020-09-24 10:50 UTC
Add a markdown document reflecting the state of our current error handling as well as our future error handling strategy as discussed in a workshop.

The future error handling strategy will be work in progress and needs to be refined.

**Comment by mossmaurice** [comment] 2020-11-04 15:35
Duplicate of #130 please continue the work there, closing this issue.

**Closed** 2020-11-13 09:59 UTC
Labels: documentation, in-review
